services:
  - type: web
    name: todovia
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py setup_oauth
      python manage.py collectstatic --noinput
    startCommand: gunicorn todo_project.wsgi:application --workers=4 --bind=0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: todo_project.settings
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: RENDER_EXTERNAL_HOSTNAME
        value: todoapp-uzg8.onrender.com
